//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int idAdministrador { get; set; }
        public string usuarioAdministrador { get; set; }
        public string contrasennaAdministrador { get; set; }
        public string nombreAdministrador { get; set; }
        public string apellidosAdministrador { get; set; }
        public Nullable<int> nivelAcceso { get; set; }
    }
}
