//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacion()
        {
            this.ReservaHabitacion = new HashSet<ReservaHabitacion>();
        }
    
        public int idHabitacion { get; set; }
        public Nullable<int> numeroHabitacion { get; set; }
        public Nullable<int> idTipoHabitacionHabitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaHabitacion> ReservaHabitacion { get; set; }
        public virtual TipoHabitacion TipoHabitacion { get; set; }
    }
}
