//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenOferta
    {
        public int idImagenOferta { get; set; }
        public Nullable<int> idImagenImagenOferta { get; set; }
        public Nullable<int> idOfertaImagenOferta { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
