//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenPublicidad
    {
        public int idImagenPublicidad { get; set; }
        public Nullable<int> idImagenImagenPublicidad { get; set; }
        public Nullable<int> iPublicidadImagenPublicidad { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Publicidad Publicidad { get; set; }
    }
}
