//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenTipoHabitacion
    {
        public int idImagenTipoHabitacion { get; set; }
        public Nullable<int> idImagenImagenTipoHabitacion { get; set; }
        public Nullable<int> idTipoHabitacionImagenTipoHabitacion { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual TipoHabitacion TipoHabitacion { get; set; }
    }
}
