//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenHotel
    {
        public int idImagenHotel { get; set; }
        public Nullable<int> idImagenImagenHotel { get; set; }
        public Nullable<int> idHotelImagenHotel { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Imagen Imagen { get; set; }
    }
}
