//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenFacilidad
    {
        public int idImagenFacilidad { get; set; }
        public Nullable<int> idImagenImagenFacilidad { get; set; }
        public Nullable<int> idFacilidadImagenFacilidad { get; set; }
    
        public virtual Facilidad Facilidad { get; set; }
        public virtual Imagen Imagen { get; set; }
    }
}
