//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HighGardenResortEntities : DbContext
    {
        public HighGardenResortEntities()
            : base("name=HighGardenResortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Facilidad> Facilidad { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<ImagenFacilidad> ImagenFacilidad { get; set; }
        public virtual DbSet<ImagenHotel> ImagenHotel { get; set; }
        public virtual DbSet<ImagenOferta> ImagenOferta { get; set; }
        public virtual DbSet<ImagenPublicidad> ImagenPublicidad { get; set; }
        public virtual DbSet<ImagenTipoHabitacion> ImagenTipoHabitacion { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<Publicidad> Publicidad { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<ReservaHabitacion> ReservaHabitacion { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<ServicioTipoHabitacion> ServicioTipoHabitacion { get; set; }
        public virtual DbSet<TipoHabitacion> TipoHabitacion { get; set; }
    }
}
