//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaHabitacion
    {
        public int idReservaHabitacion { get; set; }
        public string idReservaReservaHabitacion { get; set; }
        public Nullable<int> idHabitacionReservaHabitacion { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
