//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoHabitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoHabitacion()
        {
            this.Habitacion = new HashSet<Habitacion>();
            this.ImagenTipoHabitacion = new HashSet<ImagenTipoHabitacion>();
            this.ServicioTipoHabitacion = new HashSet<ServicioTipoHabitacion>();
        }
    
        public int idTipoHabitacion { get; set; }
        public string nombreTipoHabitacion { get; set; }
        public string descripcionTipoHabitacion { get; set; }
        public Nullable<decimal> precioTipoHabitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacion> Habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenTipoHabitacion> ImagenTipoHabitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioTipoHabitacion> ServicioTipoHabitacion { get; set; }
    }
}
